### ISSUE TITLE
DB und Tabellen anlegen

### ISSUE THREAD

**Issue by Grimmig18** [Stonks2Moon/Geschaeftskundenbroker#10]
Für Tabellen Struktur siehe https://github.com/Stonks2Moon/Geschaeftskundenbroker/blob/main/Documents/database.md

- [x] DB Anlegen
- [x] Tabellen anlegen

Geplante Zeit: 30min

**Comment by NerdyStuff** [comment]
Gebrauchte Zeit: 2h
