### ISSUE TITLE
Liquiditätsspender

### ISSUE THREAD

**Issue by NerdyStuff** [Stonks2Moon/Geschaeftskundenbroker#38]
- [ ] Rabatte von Börse weitergeben
- [x] Möglichkeit für Quotes (fertig)

**Comment by NerdyStuff** [comment]
Geplante Zeit 30h

**Comment by Grimmig18** [comment]
Marcel: +4h
Benno: +4h

**Comment by NerdyStuff** [comment]
Marcel: \+5h
Benno: \+5h

**Comment by NerdyStuff** [comment]
Quotes sind fertig:
Marcel: \+7h
Benno: +\6h

**Comment by Grimmig18** [comment]
Rabatte der Börse werden nicht weitergegeben, Feature ist zu spät von der Börse bereitgestellt und wir haben keine Zeit mehr (und kein Bock)
