### ISSUE TITLE
Vorgehen definieren

### ISSUE THREAD

**Issue by NerdyStuff** [Stonks2Moon/Geschaeftskundenbroker#5]
Arbeitsworkflow überlegen.
Z.b. Weekly, Daily, Bi-Daily

**Comment by TristanMrb** [comment]
Ergebnis in Zwischenpräsentation

**Comment by Grimmig18** [comment]
Link zur Zwischenpräsentation: https://docs.google.com/presentation/d/1Cb8AE2l7VmYS_sOGKy7eStY2TQcN3uxG/edit#slide=id.p6
