### ISSUE TITLE
Fragen:

### ISSUE THREAD

**Issue by NerdyStuff** [Stonks2Moon/Geschaeftskundenbroker#6]
- Was bedeutet Algorithmisches Handeln?
- Was ist ein Liquiditätsspender?
-> Wie werden die Rabatte weiter gegeben?
-> Welche Rabatte sollen weitergegeben werden?

**Comment by NerdyStuff** [comment]
Welche Statistiken sollen wir bereitstellen?

**Comment by NerdyStuff** [comment]
Wie gestalten sich Rabatte an die Liquiditätsspender?
Ist unser Verständnis von Quotes korrekt?

**Comment by TristanMrb** [comment]
Fragen geklärt
