### ISSUE TITLE
CSS Framework aussuchen

### ISSUE THREAD

**Issue by TristanMrb** [Stonks2Moon/Geschaeftskundenbroker#9]
geplante Zeit: 15 min

Wir haben uns für UIKit entschieden.
https://getuikit.com/docs/introduction

**Comment by Tony1704** [comment]
Wir haben uns als CSS Framework für **UIkit** entschieden. Dokumentation dafür ist [hier](https://getuikit.com/)

**Comment by TristanMrb** [comment]
benötigte Zeit: 15 min
